FROM nats:2.9.10-alpine

RUN apk add --no-cache supervisor bash

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]
COPY nats-api /usr/local/bin/
RUN chmod +x /usr/local/bin/nats-api

RUN touch /usr/local/bin/config_watcher.sh
RUN chown 1000:1000 /usr/local/bin/config_watcher.sh

RUN mkdir -p /var/log/supervisor
RUN mkdir -p /etc/supervisor/conf.d
RUN touch /etc/supervisor/conf.d/supervisor.conf
RUN chown 1000:1000 /etc/supervisor/conf.d/supervisor.conf

USER 1000

EXPOSE 4222 9235
