FROM node:16-alpine

WORKDIR /home/node/app
RUN apk add --no-cache bash
SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]
RUN npm install meshcentral
RUN chown -R node:node /home/node
EXPOSE 8080 4443
USER node
